# !/bin/bash
#                   /* ---- https://github.com/jnicolasdz ---- */                 #
# This script install astrometrica in wine and create an alias to started via CLI #
#                                 MIT License
# Copyright (c) 2025 Juan Nicolas Diaz Salamanca
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Getting Astrometrica software
link="http://iasc.cosmosearch.org/Content/Distributables/astrometrica-setup-v1.4.1.exe"
version="${link##*/}"
echo "Downloading astrometrica..."
curl -O "$link"

# Installing Astrometrica 
echo "Install astrometrica in wine..."
wine $version

# Create alias to run astrometrica via terminal
shell=$(basename $SHELL)
shell_config="."$shell"rc"
read -p "Add astrometrica command to run via terminal ? [y/n]: " add_alias
if [[ $add_alias == "y" ]]; then
    echo "Creating alias..."
    if [[ ! -f "$HOME/$shell_config" ]]; then
        echo "config shell file not found..."
        read -p "Please enter file name used for your shell configuration, e.g. .profile: " shell_config
    fi
    echo "Adding alias astrometrica to $shell_config "
    echo "# Alias for Astrometrica generated by https://github.com/jnicolasdz " >> $HOME/$shell_config
    echo "alias astrometrica='cd $HOME/.wine/dosdevices/c:/Astrometrica && wine cmd /c Astrometrica.bat && exit' " >> $HOME/$shell_config
fi

echo "Astrometrica installed successfully..."
echo "Type astrometrica in terminal to start the program"
echo "Please restart your terminal to apply changes"
